apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-cert-sync
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-cert-sync-writer
  namespace: linkerd
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["get","list","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-cert-sync-writer
  namespace: linkerd
subjects:
  - kind: ServiceAccount
    name: linkerd-cert-sync
    namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-cert-sync-writer
