apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-tools
  namespace: argocd
spec:
  description: Linkerd control plane & viz
  sourceRepos:
    - https://helm.linkerd.io/stable
    - https://github.com/nolet7/helm
    - https://github.com/nolet7/linkerd-ls
  destinations:
    - namespace: linkerd
      server: https://kubernetes.default.svc
    - namespace: linkerd-viz
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
