apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane-dev
  namespace: argocd
  annotations:
    avp.kubernetes.io/engine: "vault"
    avp.kubernetes.io/path: "kv"
    avp.kubernetes.io/vault-addr: "http://48.217.51.59:8200"
spec:
  sources:
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-control-plane
      targetRevision: 1.16.11
      helm:
        releaseName: linkerd
        valueFiles:
          - "$valuesRepo/values/values-dev.yaml"
    - repoURL: https://github.com/nolet7/helm.git
      targetRevision: main
      ref: valuesRepo
