apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: platform-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  sources:
    - repoURL: oci://ghcr.io/linkerd/charts
      chart: linkerd-control-plane
      targetRevision: "2.14.0"
      helm:
        valueFiles:
          - $values/values/values-dev.yaml
    - repoURL: https://github.com/nolet7/helm
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

